"""Adaptive phase-pressure controller driven through TraCI.

Control policy (thesis, section 6.3):  F(t+1) = argmax_k P_k(X(t))
subject to T_MIN <= T_phase <= T_MAX.

Every second while a green phase is active:
  * before T_MIN the phase is never interrupted;
  * between T_MIN and T_MAX the controller switches to the phase with the
    highest pressure if that pressure is strictly greater than the pressure
    of the current phase;
  * at T_MAX it switches to the highest-pressure *other* phase, provided that
    phase has any demand at all (otherwise it rests in the current green).

A switch runs the full transition generated by Scenario.transition()
(pedestrian clearance, amber, all-red).  The signal is driven with
setRedYellowGreenState, so SUMO never advances phases on its own.
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass, field

import traci

from .pressure import PedestrianWeights, phase_pressure
from .scenarios import Scenario

DETECTION_ZONE = 75.0   # [m] upstream of the stop line in which vehicles are counted
ARRIVAL_WINDOW = 60     # [s] moving window used to estimate lambda_i


@dataclass
class AdaptiveParams:
    t_min: int = 10
    t_max: int = 90          # selected by tune.py
    ped: PedestrianWeights = field(default_factory=PedestrianWeights)
    lane_weight: dict[str, float] = field(default_factory=dict)   # w_i, default 1


class LaneSensor:
    """Emulates a camera/loop detector on one incoming lane."""

    def __init__(self, lane: str):
        self.lane = lane
        self.length = traci.lane.getLength(lane)
        self.prev_ids: set[str] = set()
        self.arrivals: deque[int] = deque(maxlen=ARRIVAL_WINDOW)

    def update(self) -> None:
        ids = set(traci.lane.getLastStepVehicleIDs(self.lane))
        self.arrivals.append(len(ids - self.prev_ids))
        self.prev_ids = ids

    def arrival_rate(self) -> float:
        """lambda_i: vehicles that entered the lane per second (moving window)."""
        return sum(self.arrivals) / len(self.arrivals) if self.arrivals else 0.0

    def queue(self) -> int:
        """N_i: vehicles within the detection zone before the stop line."""
        start = self.length - DETECTION_ZONE
        return sum(1 for v in self.prev_ids
                   if traci.vehicle.getLanePosition(v) >= start)


class CrossingSensor:
    """Pedestrians waiting on the walking areas in front of each crossing."""

    def __init__(self, tl_id: str):
        self.prefix = f":{tl_id}_w"

    def read(self) -> dict[str, tuple[int, float]]:
        waiting: dict[str, tuple[int, float]] = {}
        for p in traci.person.getIDList():
            if not traci.person.getRoadID(p).startswith(self.prefix):
                continue
            w = traci.person.getWaitingTime(p)
            if w <= 0:
                continue
            nxt = traci.person.getNextEdge(p)
            n, t = waiting.get(nxt, (0, 0.0))
            waiting[nxt] = (n + 1, max(t, w))
        return waiting


class AdaptiveController:
    def __init__(self, scn: Scenario, mu: dict[str, float], params: AdaptiveParams):
        self.scn, self.mu, self.p = scn, mu, params
        self.lanes = {ln: LaneSensor(ln) for ph in scn.phases for ln in ph.lanes}
        self.crossings = CrossingSensor(scn.tl_id)
        self.current = 0
        self.t_green = 0
        self.queue_steps: list[tuple[str, int]] = []   # pending transition steps
        self.target: int | None = None
        self.switches = 0
        traci.trafficlight.setRedYellowGreenState(scn.tl_id, scn.phases[0].state)

    # -- pressure ----------------------------------------------------------
    def pressures(self) -> list[float]:
        peds = self.crossings.read()
        out = []
        for ph in self.scn.phases:
            lanes = [(s.queue(), s.arrival_rate(), self.mu[ln],
                      self.p.lane_weight.get(ln, 1.0))
                     for ln, s in ((ln, self.lanes[ln]) for ln in ph.lanes)]
            crossings = [peds.get(c, (0, 0.0)) for c in ph.crossings]
            out.append(phase_pressure(lanes, crossings, self.p.ped, s_k=1.0))
        return out

    # -- main loop -----------------------------------------------------------
    def step(self) -> None:
        """Call once after every traci.simulationStep()."""
        for s in self.lanes.values():
            s.update()

        if self.queue_steps or self.target is not None:
            self._advance_transition()
            return

        self.t_green += 1
        if self.t_green < self.p.t_min:
            return
        P = self.pressures()
        k = self.current
        if self.t_green >= self.p.t_max:
            others = [j for j in range(len(P)) if j != k]
            best = max(others, key=lambda j: P[j])
            if P[best] > 0:
                self._start_transition(best)
            return
        best = max(range(len(P)), key=lambda j: P[j])
        if best != k and P[best] > P[k]:
            self._start_transition(best)

    def _start_transition(self, dst: int) -> None:
        self.switches += 1
        self.target = dst
        self.queue_steps = []
        for state, dur in self.scn.transition(self.current, dst):
            self.queue_steps += [(state, 1)] * dur
        self._advance_transition()

    def _advance_transition(self) -> None:
        if self.queue_steps:
            state, _ = self.queue_steps.pop(0)
            traci.trafficlight.setRedYellowGreenState(self.scn.tl_id, state)
            return
        self.current = self.target
        self.target = None
        self.t_green = 0
        traci.trafficlight.setRedYellowGreenState(
            self.scn.tl_id, self.scn.phases[self.current].state)
