"""Baseline signal programs written as SUMO <tlLogic> additional files.

* Fixed-time: cycle length and green splits computed with Webster's method
  from the expected demand and the measured saturation flow.
* Actuated:  SUMO's built-in gap-based actuated controller (type="actuated")
  with the same minimum/maximum green as the adaptive controller.

Both use the same transition intervals (pedestrian clearance, amber,
all-red) as the adaptive controller, generated by Scenario.transition().
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .scenarios import Scenario

T_MIN = 10   # minimum green [s] (also minimum pedestrian walk time)
T_MAX = 40   # maximum green [s]
C_MIN, C_MAX = 30, 120


@dataclass
class WebsterPlan:
    cycle: float
    greens: list[float]       # vehicle green per phase, including ped clearance
    flow_ratios: list[float]
    lost_time: float


def _continuing(scn: Scenario, src: int, dst: int) -> int:
    """Seconds of the transition during which src vehicles still have green."""
    steps = scn.transition(src, dst)
    veh_links = [i for i, c in enumerate(scn.phases[src].state)
                 if c in "Gg" and i not in scn.crossing_links]
    if steps and veh_links and all(steps[0][0][i] in "Gg" for i in veh_links):
        return steps[0][1]
    return 0


def webster(scn: Scenario, demand: dict[str, float], mu: dict[str, float]) -> WebsterPlan:
    """Webster (1958): C0 = (1.5 L + 5) / (1 - Y), greens split by y_k / Y.

    A phase that serves no vehicles (the pedestrian phase of the simple
    intersection) gets the minimum walk time T_MIN and that time is counted
    as lost time for the vehicle phases.

    Minimum green: every phase shows its full green for at least T_MIN
    *before* its transition starts (the same rule as the adaptive
    controller).  Vehicle greens include the pedestrian-clearance interval
    during which vehicles keep moving, so their minimum is T_MIN + that
    interval.  If a minimum is binding, the cycle grows accordingly.
    """
    n = len(scn.phases)
    y = [max((demand.get(ln, 0.0) / mu[ln] for ln in p.lanes), default=0.0)
         for p in scn.phases]
    lost = 0.0
    for k in range(n):
        nxt = (k + 1) % n
        lost += scn.lost_time(k, nxt) - _continuing(scn, k, nxt)
        if not scn.phases[k].lanes:
            lost += T_MIN
    Y = sum(y)
    cycle = C_MAX if Y >= 0.95 else (1.5 * lost + 5) / (1 - Y)
    cycle = min(max(cycle, C_MIN), C_MAX)
    effective = cycle - lost
    greens = []
    for k, p in enumerate(scn.phases):
        if not p.lanes:
            greens.append(float(T_MIN))
        else:
            g_min = T_MIN + _continuing(scn, k, (k + 1) % n)
            greens.append(max(g_min, effective * y[k] / Y if Y > 0 else effective / n))
    cycle = lost + sum(g for g, p in zip(greens, scn.phases) if p.lanes)
    return WebsterPlan(cycle, greens, y, lost)


def _phase_xml(state: str, duration: float, min_dur: float | None = None,
               max_dur: float | None = None, name: str = "") -> str:
    extra = ""
    if min_dur is not None:
        extra = f' minDur="{min_dur:g}" maxDur="{max_dur:g}"'
    label = f' name="{name}"' if name else ""
    return f'        <phase duration="{round(duration)}" state="{state}"{extra}{label}/>'


def _program(scn: Scenario, program_id: str, kind: str, greens: list[tuple]) -> str:
    n = len(scn.phases)
    lines = [f'    <tlLogic id="{scn.tl_id}" type="{kind}" programID="{program_id}" offset="0">']
    if kind == "actuated":
        lines += ['        <param key="max-gap" value="3.0"/>',
                  '        <param key="detector-gap" value="2.0"/>',
                  '        <param key="passing-time" value="2.0"/>']
    for k, p in enumerate(scn.phases):
        nxt = (k + 1) % n
        cont = _continuing(scn, k, nxt)
        dur, lo, hi = greens[k]
        if lo is None:
            lines.append(_phase_xml(p.state, max(dur - cont, 1), name=p.name))
        else:   # actuated: same T_min / T_max rule as the adaptive controller
            lines.append(_phase_xml(p.state, lo, lo, hi, p.name))
        for state, d in scn.transition(k, nxt):
            lines.append(_phase_xml(state, d))
    lines.append("    </tlLogic>")
    return "\n".join(lines)


def write_fixed_time(scn: Scenario, plan: WebsterPlan, out: Path) -> Path:
    body = _program(scn, "webster", "static", [(g, None, None) for g in plan.greens])
    out.write_text(f"<additional>\n{body}\n</additional>\n")
    return out


def write_actuated(scn: Scenario, out: Path, t_max: int = T_MAX) -> Path:
    greens = []
    for p in scn.phases:
        if p.lanes:
            greens.append((T_MIN, T_MIN, t_max))
        else:   # pedestrian-only phase: no vehicle detectors, fixed walk time
            greens.append((T_MIN, None, None))
    body = _program(scn, "actuated", "actuated", greens)
    out.write_text(f"<additional>\n{body}\n</additional>\n")
    return out
